### ISSUE TITLE
Inconsistent `tagof` return for `_:`.

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/compiler#160]
```pawn
Tagof(var, tag1 = tagof (var))
{
	new tag2 = tagof (var);
	printf("%d %x", var, tag1);
	printf("%d %x", var, tag2);
}

main()
{
	Tagof(4);
}
```

Expected output should be something consistent, either:

```
4 0
4 0
```

Or:

```
4 80000000
4 80000000
```

Most tags seem to have the top bit set, but in some of my experiments, the default `_:` tag was just `0` - which is quite nice in some ways to distinguish it from other tags.  However, the actual output is both:

```
4 0
4 80000000
```

**Comment by Y-Less** [comment]
`tagof (_:)` returns `0x80000000`.

**Comment by YashasSamaga** [comment]
The compiler seems to do some mysterious stuff:

`tagsym=find_constval_byval(&tagname_tab,tag | PUBLICTAG);`

`PUBLICTAG` is `0x80000000Lu`

What's a public tag?

**Comment by Y-Less** [comment]
No.  I did some research a while ago.  A public tag is just like any other public thing - the name is in the AMX header.  A `fixed` tag is a strong tag - I've never seen the `fixed` name before.

https://github.com/Zeex/amx_assembly/blob/c390cbebfa6e88425205ec21577ed09e34e7229b/amx_header.inc#L33-L34

**Comment by YashasSamaga** [comment]
What kind of tags do not end up in the AMX header?

**Comment by Y-Less** [comment]
Only `_:` AFAIK.

**Comment by YashasSamaga** [comment]
How about forcing `_:` (as 0x80000000) to be present in the tag table irrespective of whether that tag has been used? (not sure if there's a meaningful script which doesn't use it).

**Comment by Y-Less** [comment]
Why?  That doesn't add anything and doesn't solve anything.  The bug was that `_:` is sometimes `cellmin` and sometimes `0`.  I suppose forcing it in to the table might fix it in a round-about way by making it always `cellmin`, but I'm not convinced unless what I suspect is an underlying bug is fixed to stop the inconsistency.

**Comment by YashasSamaga** [comment]
This seems even more complicated:

```
func(MyTag:arg) { }
main ()
{
    func(5);
}
```

`tag mismatch: expected tag(s) "MyTag" or "", but found "_"`

What is `""` supposed to represent? If it represents an untagged cell, then the warning shouldn't have been triggered in the first place.

**Comment by YashasSamaga** [comment]
I did a comparison between the free standing tagof  operator code and the tagof used as default argument.

The free standing tagof operator has the following code for symbols:

```
tag=sym->tag;
.
.
.
 exporttag(tag);
    clear_value(lval);
    lval->ident=iCONSTEXPR;
    lval->constval=tag | PUBLICTAG;
    ldconst(lval->constval,sPRI);
```

`sym` is the symbol inside the tagof parenthesis. Here `sym->tag` can be zero. Even if it is zero, the code which follows it in the above snippet is executed. This would mean that `0` would be exported to the tags table (the `exporttag` function internally checks if the `PUBLICTAG` bit is set; if set, it ignores as it is already present in the tags table). The actual value which is returned by `tagof` is stored in the lvalue as `tag | PUBLICTAG` which is why you get `0x80000000` when `tagof` operator is used directly.

The code which handles tagof as default argument is a bit more involved. The compiler creates a local (as in a local variable in the compiler code) tag table (has nothing to do with the one in the AMX header; this is just for the compiler to keep track of tags in a function).

For each argument, it pushes the tag name and it's value to the local tag table IF AND ONLY IF the tag value is NOT `0`.

```
if (lval.tag!=0)
            append_constval(&taglst,arg[argidx].name,lval.tag,0);
```

Hence, for untagged arguments, the untagged tag (`_:`??) entry does not exist in the local tab table.

When the compiler finds that an argument has `tagof` as default value, it has the following code:

```
asz=find_constval(&taglst,arg[argidx].defvalue.size.symname,
                        arg[argidx].defvalue.size.level);
      if (asz != NULL) {
        exporttag(asz->value);
        array_sz=asz->value | PUBLICTAG;  /* must be set, because it just was exported */
      } else {
        array_sz=0;
      } /* if */
```

In the untagged case, `asz` will be `NULL` as an entry in the local tag table does not exist for untagged tag. Because of this, `arrary_sz` is set to `0` and this value is what is pushed as argument to the function later.

The differences as stated earlier between the two is that the standalone tagof operator exports the untagged tag after which it sets the `PUBLICTAG` bit but the tagof operator used as default argument does not export (and hence doesn't bother setting the `PUBLICTAG` bit).

While it makes no sense why someone would do this but I think the fix is to make the tagof operator used as default argument behave like the standalone tagof operator by exporting the `0` tag and setting the `PUBLICBIT`.

**Comment by YashasSamaga** [comment]
I'm not sure what's the bug.

```
SC_FUNC void exporttag(int tag)
{
  /* find the tag by value in the table, then set the top bit to mark it
   * "public"
   */
  if (tag!=0 && (tag & PUBLICTAG)==0) {
    constvalue *ptr;
    for (ptr=tagname_tab.next; ptr!=NULL && tag!=(int)(ptr->value & TAGMASK); ptr=ptr->next)
      /* nothing */;
    if (ptr!=NULL)
      ptr->value |= PUBLICTAG;
  } /* if */
}
```

The `exporttag` function ignores tag values with zero which explains why `0` doesn't end up in the tag table in the AMX header.

If untagged tag is not exported, then it should actually be zero? So if we go by the meaning of the `PUBLICTAG` bit, the bug should then be tagof operator returning `0x80000000`?

**Comment by YashasSamaga** [comment]
The general procedure for adding the tag is:
- if a tag is found, it is added to the tag list (list of all tags: both public and non-public)
- if necessary, the tag is exported

The `exporttag` function is used to export the tag. This function expects the tag to be present in the tag list. All this function does is sets the `PUBLICTAG` bit of the tag in the tag list.

The compiler tries to export tags of symbols which are passed to `tagof`.

**Verification:**
```
new MyTag:a = 1;
	printf("%x",tagof(a));
```

ends up giving

`Writing to tag table: "MyTag" 1073741850 (after masking) -1073741798(before masking)`

If a label is passed as an argument to `tagof`, it does not add it to the tag table because the tag entry doesn't even exist in the tag list for `exporttag` to set the `PUBLICTAG`.

Whether this is a bug or not is up for speculation. I think the tags which are passed as labels to tagof and weren't used before are not added to the tag table because they aren't needed.

**Comment by YashasSamaga** [comment]
The issue now is what should `tagof(_:)` return. In my opinion,  the standalone tagof operator is getting it wrong. As the untagged tag is not exported to the tag table, the tag identifier for untagged cells must be 0.

If we can get as consenus on what the tag identifier for untagged cells must be,  the issue will be resolved. It takes editing of just 3 lines to patch this either way (0 or 0x80000...)

**Comment by Y-Less** [comment]
I'd vote `0`.  As you say it isn't public, and `0` is close to `none` which `_` almost is.
