### ISSUE TITLE
Main code "stock" warning.

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/compiler#203]
We could add a warning for when `stock` is used in any file not included from under `-i` directories.  It would be nice, but I don't know if assuming that `-i` denotes only library includes is sufficient.  Though I suspect it should be - even nicely modular large modes don't use those for their composite parts.

**Comment by Southclaws** [comment]
Now I use -i for basically everything due to how sampctl works but back when I used a monorepo with a modular gamemode, I still had unused stocks in the core codebase because I developed modules as if they were libraries that others could use (hence the birth of sampctl...).

I see the value in this but I don't think it's worth the time, stocks wouldn't be compiled anyway so why notify the user? They might be planning to use them later on in development.
