### ISSUE TITLE
Input file is deleted

### ISSUE THREAD

**Issue by Zeex** [pawn-lang/compiler#206]
```
pawncc a.pwn b.pwn
```

b.pwn is deleted 👍 

(Although it doesn't compile anyway, the default SA-MP compiler doesn't delete the file)

**Comment by SimonItaly** [comment]
I've tried this with the latest release, a.pwn and b.pwn were the same file with the following code.
```pawn
main()
{
        new a = 1;
        return a;
}
```
I've added some debug prints around every _remove_ function in _sc1.c_, that's the result:
![schermata da 2017-11-07 16-54-30](https://user-images.githubusercontent.com/6637624/32503012-73e70f16-c3dc-11e7-8c65-c0249bc757f6.png)

https://github.com/Zeex/pawn/blob/c2a92d9bf320a87285dd0f107e9b7043ac065ced/source/compiler/sc1.c#L759

Apparently the compiler tries to concatenate the files. The last input file is always deleted.
I've tried this with three files with different function names.

![schermata da 2017-11-07 17-07-22](https://user-images.githubusercontent.com/6637624/32503704-342ea602-c3de-11e7-9830-02b8eada3f94.png)

![schermata da 2017-11-07 17-07-37](https://user-images.githubusercontent.com/6637624/32503728-3f2077f2-c3de-11e7-9bf3-364f0301a482.png)

I've also noticed that /tmp is filled the temporary files that should be deleted instead of the original source.
```bash
-rw------- 1 simone simone  109 nov  7 17:04 pawn1EGtdM
-rw------- 1 simone simone    0 ott 24 16:11 pawnC3WGo1
-rw------- 1 simone simone    0 ott 24 16:11 pawnE2tC9l
-rw------- 1 simone simone  100 nov  7 16:54 pawnLsOJDW
-rw------- 1 simone simone  100 nov  7 16:39 pawnVtDhtY
-rw------- 1 simone simone  157 nov  7 17:06 pawnY8RJeg # that's the one generated above
-rw------- 1 simone simone   54 nov  7 16:38 pawnc9my6g
-rw------- 1 simone simone  100 nov  7 16:39 pawncKKdjz
-rw------- 1 simone simone   99 nov  7 16:43 pawneKteAg
-rw------- 1 simone simone   50 nov  7 16:53 pawniiSwdO
-rw------- 1 simone simone  100 nov  7 16:39 pawnkgkL6q
-rw------- 1 simone simone   99 nov  7 16:41 pawnnW4ZOg
-rw------- 1 simone simone  100 nov  7 16:53 pawnwhWjMS
```
