### ISSUE TITLE
#pragma tabsize 0 dont work

### ISSUE THREAD

**Issue by taktaz208** [pawn-lang/compiler#304]
Hello , i've a gamemode code that is very bad written by an old scripter. it have alot of "warning 217: loose indentation" warning and i want hide them but it dont work.

Thanks for all things.

**Comment by Y-Less** [comment]
That's not a bug - that's a feature.  Fix your code!

**Comment by Y-Less** [comment]
To clarify - `#pragma tabsize 0` was explicitly removed because it encourages bad coding practices, like the ones you are trying to use here.  Instead of ignoring the warnings, actually take them for what they are - information about problems in your script, and fix those problems.  Indentation is not hard - if you see `{` go deeper, if you see `}`, go shallower.

**Comment by Jeroen52** [comment]
If I were you I'd even turn on Hardmode using -E+

Not really that it is hardmode, you're supposed to write code that doesn't give any warnings.
