### ISSUE TITLE
Compiler result cut off

### ISSUE THREAD

**Issue by r1ght00** [pawn-lang/compiler#337]
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [x] Bug Report
* [ ] Feature Request
* [ ] Question

**What happened**:
The compiled result is cut off

**What you expected to happen**:
Shows result like normal
**How to reproduce it (as minimally and precisely as possible)**:
Just compile(in my case) with warning or error.
**Anything else we need to know?**:
It also shows wrong total warnings or errors,depends what is the top of the result.(warnings/errors - 1)
so,it somehow ignores the result that get cut off.
see: https://i.imgur.com/5FggS9M.png , the bottom left result is different with one in the terminal.
This doesn't always happened but it's annoying https://pastebin.com/zCcjZA62(first and last result).
I've tried this with other scripts with same compiler,it also happened.
**Environment**:

* Operating System: Windows 10
* Compiler version: 3.10.8
* How are you invoking the compiler? : vscode

**Comment by Southclaws** [comment]
This is a bug in the terminal in Visual Studio Code - I believe to fix it, you just need to have the terminal open *once* while a build completes then you can close it and ignore it after that. I think this is because the terminal buffer size is set automatically but it only adapts when you have the window focused.

There's probably an open issue for this on the [vscode GitHub page](https://github.com/Microsoft/vscode), but I've not attempted to find it yet.

**Comment by r1ght00** [comment]
Is there any reason why it only happened in the latest version of the
compiler? I never get this kind of bug on previous releases.

**Comment by Southclaws** [comment]
I've had this with all commands in vscode, sampctl, linters, compilers.

**Comment by r1ght00** [comment]
Yes,I have been inactive for a while,sorry.
