### ISSUE TITLE
#pragma option limited to 31 characters

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/compiler#359]
### Issue description:

Using an option over 31 characters (I assume 32 with NULL) crashes the compiler.

### Minimal complete verifiable example (MCVE):

```pawn
// It doesn't even matter if this exists or not.
#pragma option -idependencies\y_thirdpartyinclude
```

### Workspace Information:

* Compiler version:
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by YashasSamaga** [comment]
The directive has a limit of 31 (`sNAMEMAX`) characters but `parseoptions()` (which the directive invokes)  uses `_MAX_PATH` as the limit. 

A quick solution could be to use `_MAX_PATH` as the limit in the directive.

Irrespective of the length, the compiler shouldn't have crashed. The problem seems to be with the logic used:

```
char name[sNAMEMAX+1];
.
.
.
for (i=0; i<sizeof name && *lptr>' '; i++,lptr++)
    name[i]=*lptr;
 name[i]='\0';
```

what if the loop breaks because `i` took `sizeof(name)`? The `name[i]='\0';` attempts to modify one past the end of the array.
