### ISSUE TITLE
warning 232: output file is written, but with compact encoding disabled

### ISSUE THREAD

**Issue by Zorono** [pawn-lang/compiler#482]
## Issue description:
Information that could be useful:
- how to reproduce the problem: `#pragma option -d2` with `3.10.9`
- observed behavior: very large AMX size
- expected behavior: debugging level 2 and normal optimized AMX file
- other relevant information: `warning 232: output file is written, but with compact encoding disabled`

### Workspace Information:

* Compiler version: `3.10.9`
* Command line arguments provided (or sampctl version): `grandlarcyllol.pwn -;+ -(+ -d2 -O1 -Z -C+ -D"gamemodes"`
* Operating System: Windows 8.1 Pro x32

**Comment by Daniel-Cortez** [comment]
I suspect the reason of this is the out-of-bounds array access bug in `encode_cell()`, which most probably clobbers the value in the `bytes_out` variable, as it's located right before the encoding buffer in memory. This should be fixed in the upcoming release (see #423).
(Not sure what keeps the maintainers from making that next release though; there's already a lot of bugfixes and new functionality accumulated during the last one and a half years since the previous release.)

**Comment by Y-Less** [comment]
No reason at all, just haven't got around to it.  You're probably right that a new release is overdue.  @Zeex @Southclaws?

**Comment by Y-Less** [comment]
The last time I tried to make a release I horribly screwed it up, so...

**Comment by Zeex** [comment]
I can try, just need to make a changelog out of git commits (it can take a while)

**Comment by Zorono** [comment]
Thanks a lot guys, after upgrading to `v3.10.10` it is solved! :dancer:
