### ISSUE TITLE
Just wondering

### ISSUE THREAD

**Issue by Zorono** [pawn-lang/compiler#491]
What does the following pragmas do ???
```
#pragma disablerecursion
#pragma warning push
#pragma warning pop
```
and what is the current value of `__Pawn`

Edit: just found the value of `__Pawn`
0x030A =  778

**Comment by Y-Less** [comment]
The first pragma disables a stupid setting on an obscure build of the compiler (known as the "Russian Compiler").  It isn't actually in this version of the compiler, which is why when YSI disables it it first disables the `unknown pragma` warning so you don't get extra warnings in this compiler.

The other two save and restore the currently enabled warnings.
